### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by stepbysec** [certmichelin/Redscan#12]
Hello,

I wanted to quickly spin up a demo VM following your podcast on NoLimitSecu ;).
What are the hardware requirements in terms of CPU, RAM and hard disk space?

**Comment by AskenzSec** [comment]
Hello!

The hardware requirement depends essentially on what you want to scan. 
By the way, for a demo 16Gb of ram will be enough. The cpu load is insignifiant and of course a good network connection is important

The demo mode will only privision only one instance per plugin. If you want to optimize the memory, you could disable some plugins from the docker-compose file.

Don't hesitate to come back us with your feedback !!
