### ISSUE TITLE
[Chore] Documentation fixes

### ISSUE THREAD

**Issue by noraj** [certmichelin/Redscan#13]
Some changes may be needed in the documentation :

## GHCR

https://github.com/certmichelin/Redscan/wiki

```diff
-docker login https://docker.pkg.github.com
+docker login https://ghcr.io
```

## dockprom

https://github.com/certmichelin/Redscan/blob/51b8a374ec842bd2c4ecca927ce0801f08a8e544/red.py#L127

https://github.com/certmichelin/Redscan/blob/51b8a374ec842bd2c4ecca927ce0801f08a8e544/red.py#L133

`python red.py --demo` and `python red.py --fun` fails.

![image](https://user-images.githubusercontent.com/16578570/156893386-2df8b37f-abb9-4c40-b4eb-a76e560a6a0d.png)

Underneath it launches `docker-compose -f dockprom/docker-compose.yml up -d`

but dockprom requires creds cf. https://github.com/stefanprodan/dockprom#install

```
ADMIN_USER=admin ADMIN_PASSWORD=admin ADMIN_PASSWORD_HASH=JDJhJDE0JE91S1FrN0Z0VEsyWmhrQVpON1VzdHVLSDkyWHdsN0xNbEZYdnNIZm1pb2d1blg4Y09mL0ZP docker-compose -f dockprom/docker-compose.yml up -d
```

So then I have dockprom running but this stem fails with the same error

https://github.com/certmichelin/Redscan/blob/51b8a374ec842bd2c4ecca927ce0801f08a8e544/red.py#L134

```
error getting credentials - err: exit status 1, out: `exit status 2: gpg: decryption failed: No secret key`
```

So does something changed from the actual README steps to setup the demo environment that is not documented yet?

**update**: seems to be related to [docker-credential-helpers](https://github.com/docker/docker-credential-helpers/issues/118) not prompting for passphrase. I [login to GHCR with a PAT](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry) and use [docker-credential-helpers](https://github.com/docker/docker-credential-helpers) to store credentials in a safe way.

**Comment by AskenzSec** [comment]
Hello, @noraj,

I've updated the wiki according to your remarks, thanks a lot for your feedback !!

I'm quite suprised with the issues you had with docker login we never had issues with this step. I'm not sure to understand your last sentence, did you finally succeed to run the demo?

**Comment by noraj** [comment]
> I'm quite suprised with the issues you had with docker login we never had issues with this step. I'm not sure to understand your last sentence, did you finally succeed to run the demo?

No I didn't succeed but I know the origin. It's not a RedScan issue.
